INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Electronics',NOW());
INSERT INTO TB_CATEGORY (NAME,created_at) VALUES('Computers',NOW());
